use crate::architecture::Room;
use crate::materials::pbr::PbrMaterial;
use crate::mechanics::statics::Truss;
use serde::Serialize;
use std::fs;
use std::path::Path;

#[derive(Serialize)]
pub struct BlenderCityData<'a> {
    pub rooms: &'a [Room],
    pub truss: &'a Truss,
    pub material: &'a PbrMaterial,
}

pub struct BlenderExporter;

impl BlenderExporter {
    pub fn export_megacity(rooms: &[Room], truss: &Truss, material: &PbrMaterial) {
        let export_dir = Path::new("public/blender");
        fs::create_dir_all(export_dir).unwrap();

        let data = BlenderCityData {
            rooms,
            truss,
            material,
        };

        let json_data = serde_json::to_string_pretty(&data).unwrap();
        fs::write(export_dir.join("megacity_data.json"), json_data).unwrap();

        let sgo_script = format!(r#"
// SEARU MegaCity Physics & Topology (.sgo)
// Generated by ScriptGo VM (Aerospace Grade)
// Rooms: {}
// Bars: {}

LOADIMM 1 100 // Initialize Physics Loop
LOADIMM 2 0
ADD 3 1 2

// ... AOT Native Physics calculations ...
HALT
"#, rooms.len(), truss.bars.len());

        fs::write(export_dir.join("megacity_physics.sgo"), sgo_script).unwrap();
    }
}
