use crate::architecture::Room;
use crate::mechanics::statics::Truss;
use std::fs;
use std::path::Path;

pub struct GCodeExporter;

impl GCodeExporter {
    pub fn export_megacity(rooms: &[Room], truss: &Truss) {
        let export_dir = Path::new("public/gcode");
        if !export_dir.exists() {
            fs::create_dir_all(export_dir).unwrap();
        }

        let mut gcode = String::new();

        // --- Start Code ---
        gcode.push_str("; MegaCity Autonomous Extrusion G-Code\n");
        gcode.push_str("; Generated by SEARU MegaCityPipeline\n");
        gcode.push_str("G21 ; Set units to millimeters\n");
        gcode.push_str("G90 ; Use absolute coordinates\n");
        gcode.push_str("M104 S200 ; Set extruder temp\n");
        gcode.push_str("M140 S60 ; Set bed temp\n");
        gcode.push_str("G28 ; Home all axes\n");
        gcode.push_str("G1 Z5 F5000 ; Lift nozzle\n");
        gcode.push_str("M109 S200 ; Wait for extruder temp\n");
        gcode.push_str("G92 E0 ; Reset extruder\n");

        // We will simulate printing 10 layers of the building walls (Z-height from 0 to 2mm)
        let num_layers = 10;
        let layer_height = 0.2;
        let scale = 0.5; // Scale SVG coords down to fit on a standard 200x200mm bed
        let offset = 100.0; // Center print on bed

        let mut current_e = 0.0;

        gcode.push_str("\n; --- Architectural Walls ---\n");
        for layer in 0..num_layers {
            let z = (layer as f64) * layer_height + layer_height;
            gcode.push_str(&format!("; Layer {}\n", layer));
            gcode.push_str(&format!("G1 Z{:.2} F5000\n", z));

            for r in rooms {
                let x1 = (r.x - 400.0) * scale + offset;
                let y1 = (r.y - 400.0) * scale + offset;
                let x2 = x1 + (r.w * scale);
                let y2 = y1 + (r.h * scale);

                // Move to start of room (no extrusion)
                gcode.push_str(&format!("G1 X{:.2} Y{:.2} F5000\n", x1, y1));
                
                // Extrude perimeter
                let feedrate = 1200;
                
                // Line 1: (x1, y1) to (x2, y1)
                current_e += (x2 - x1) * 0.03;
                gcode.push_str(&format!("G1 X{:.2} Y{:.2} E{:.4} F{}\n", x2, y1, current_e, feedrate));
                
                // Line 2: (x2, y1) to (x2, y2)
                current_e += (y2 - y1) * 0.03;
                gcode.push_str(&format!("G1 X{:.2} Y{:.2} E{:.4}\n", x2, y2, current_e));
                
                // Line 3: (x2, y2) to (x1, y2)
                current_e += (x2 - x1) * 0.03;
                gcode.push_str(&format!("G1 X{:.2} Y{:.2} E{:.4}\n", x1, y2, current_e));
                
                // Line 4: (x1, y2) to (x1, y1)
                current_e += (y2 - y1) * 0.03;
                gcode.push_str(&format!("G1 X{:.2} Y{:.2} E{:.4}\n", x1, y1, current_e));
            }
        }

        // We will simulate printing 2 layers of the Vibration Damping Truss across the floor
        gcode.push_str("\n; --- Vibration Damping Truss ---\n");
        let z = layer_height * 2.0;
        gcode.push_str(&format!("G1 Z{:.2} F5000\n", z));
        
        for bar in &truss.bars {
            let n1 = &truss.nodes[bar.node_a];
            let n2 = &truss.nodes[bar.node_b];
            
            let x1 = ((n1.x * 80.0) - 400.0) * scale + offset;
            let y1 = ((n1.y * 80.0) - 400.0) * scale + offset;
            let x2 = ((n2.x * 80.0) - 400.0) * scale + offset;
            let y2 = ((n2.y * 80.0) - 400.0) * scale + offset;
            
            // Move to start node (retract first to avoid stringing)
            current_e -= 1.0;
            gcode.push_str(&format!("G1 E{:.4} F2400 ; Retract\n", current_e));
            gcode.push_str(&format!("G1 X{:.2} Y{:.2} F5000\n", x1, y1));
            current_e += 1.0;
            gcode.push_str(&format!("G1 E{:.4} F2400 ; Un-retract\n", current_e));
            
            // Extrude bar
            let dist = ((x2 - x1).powi(2) + (y2 - y1).powi(2)).sqrt();
            current_e += dist * 0.04; // Trusses are thicker
            gcode.push_str(&format!("G1 X{:.2} Y{:.2} E{:.4} F1000\n", x2, y2, current_e));
        }

        // --- End Code ---
        gcode.push_str("\n; --- End Code ---\n");
        current_e -= 3.0; // Big retract at end
        gcode.push_str(&format!("G1 E{:.4} F2400\n", current_e));
        gcode.push_str("G91 ; Relative positioning\n");
        gcode.push_str("G1 Z10 F5000 ; Lift nozzle clear\n");
        gcode.push_str("G90 ; Absolute positioning\n");
        gcode.push_str("G28 X0 Y0 ; Home X/Y\n");
        gcode.push_str("M104 S0 ; Turn off extruder\n");
        gcode.push_str("M140 S0 ; Turn off bed\n");
        gcode.push_str("M84 ; Disable motors\n");

        let file_path = export_dir.join("megacity.gcode");
        fs::write(file_path, gcode).unwrap();
        println!("[GCodeExporter] Successfully compiled to G-Code: public/gcode/megacity.gcode");
    }
}
